# coding: utf-8

"""
    DJ server

    A DataJunction metrics repository  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g2c5d4fa
    Generated by: https://openapi-generator.tech
"""

import unittest

import dj_python_client
from dj_python_client.model.column_metadata import ColumnMetadata
from dj_python_client import configuration


class TestColumnMetadata(unittest.TestCase):
    """ColumnMetadata unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
