# coding: utf-8

"""
    DJ server

    A DataJunction metrics repository  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g2c5d4fa
    Generated by: https://openapi-generator.tech
"""

from dj_python_client.paths.graphql.get import HandleHttpGetGraphqlGet
from dj_python_client.paths.graphql.post import HandleHttpPostGraphqlPost
from dj_python_client.paths.databases_.get import ReadDatabasesDatabasesGet
from dj_python_client.paths.metrics_node_id_.get import ReadMetricMetricsNodeIdGet
from dj_python_client.paths.metrics_node_id_data_.get import ReadMetricsDataMetricsNodeIdDataGet
from dj_python_client.paths.metrics_.get import ReadMetricsMetricsGet
from dj_python_client.paths.metrics_node_id_sql_.get import ReadMetricsSqlMetricsNodeIdSqlGet
from dj_python_client.paths.nodes_.get import ReadNodesNodesGet
from dj_python_client.paths.queries_query_id_.get import ReadQueryQueriesQueryIdGet
from dj_python_client.paths.queries_.post import SubmitQueryQueriesPost


class DefaultApi(
    HandleHttpGetGraphqlGet,
    HandleHttpPostGraphqlPost,
    ReadDatabasesDatabasesGet,
    ReadMetricMetricsNodeIdGet,
    ReadMetricsDataMetricsNodeIdDataGet,
    ReadMetricsMetricsGet,
    ReadMetricsSqlMetricsNodeIdSqlGet,
    ReadNodesNodesGet,
    ReadQueryQueriesQueryIdGet,
    SubmitQueryQueriesPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
