# coding: utf-8

"""
    DJ server

    A DataJunction metrics repository  # noqa: E501

    The version of the OpenAPI document: 0.0.post1.dev1+g2c5d4fa
    Generated by: https://openapi-generator.tech
"""

from djclient.paths.graphql.get import HandleHttpGetGraphqlGet
from djclient.paths.graphql.post import HandleHttpPostGraphqlPost
from djclient.paths.databases_.get import ReadDatabasesDatabasesGet
from djclient.paths.metrics_node_id_.get import ReadMetricMetricsNodeIdGet
from djclient.paths.metrics_node_id_data_.get import ReadMetricsDataMetricsNodeIdDataGet
from djclient.paths.metrics_.get import ReadMetricsMetricsGet
from djclient.paths.metrics_node_id_sql_.get import ReadMetricsSqlMetricsNodeIdSqlGet
from djclient.paths.nodes_.get import ReadNodesNodesGet
from djclient.paths.queries_query_id_.get import ReadQueryQueriesQueryIdGet
from djclient.paths.queries_.post import SubmitQueryQueriesPost


class DefaultApi(
    HandleHttpGetGraphqlGet,
    HandleHttpPostGraphqlPost,
    ReadDatabasesDatabasesGet,
    ReadMetricMetricsNodeIdGet,
    ReadMetricsDataMetricsNodeIdDataGet,
    ReadMetricsMetricsGet,
    ReadMetricsSqlMetricsNodeIdSqlGet,
    ReadNodesNodesGet,
    ReadQueryQueriesQueryIdGet,
    SubmitQueryQueriesPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
