name: Bump Version
on:
  workflow_dispatch:
    inputs:
      library:
        type: choice
        description: Which library to bump
        required: true
        options:
          - server
          - client
      bump:
        type: choice
        description: Hatch version bump rule
        required: true
        options:
          - release
          - major
          - minor
          - patch
          - alpha
          - beta
          - rc
          - post
          - dev

jobs:
  publish:
    env:
      PDM_DEPS: 'urllib3<2'
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: ${{ github.event.inputs.library == 'server' && '.' || './client/python' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - uses: pdm-project/setup-pdm@v3
        name: Setup PDM
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          prerelease: true
          enable-pep582: true

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Bump release version with hatch and commit
        run: |
          hatch version ${{ github.event.inputs.bump }}
          export NEW_VERSION=v$(hatch version)
          export LIBRARY=${{ github.event.inputs.library }}
          git commit -am "Bumping $LIBRARY to version $NEW_VERSION"
          git checkout -b releases/$LIBRARY-$NEW_VERSION
          git push --set-upstream origin releases/$LIBRARY-$NEW_VERSION -f
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Open a PR with the version bump
        run: |
          export NEW_VERSION=v$(hatch version)
          export LIBRARY=${{ github.event.inputs.library }}
          gh pr create -B main -H "releases/$LIBRARY-$NEW_VERSION" --title "Bumping $LIBRARY to version $NEW_VERSION" --body "This is an automated PR triggered by the Bump Version action. Merging this PR will bump the DataJunction $LIBRARY to version $NEW_VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
