name: Generate Clients From OpenAPI Spec
on:
  push:
    branches:
      - main
jobs:
  generate-python-client:
    runs-on: ubuntu-latest
    name: Generate Python Client
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Python client
        uses: openapi-generators/openapitools-generator-action@v1.4.0
        with:
          generator: python
          openapi-file: openapi.json
          config-file: ./.github/files/python-client-gen.yml

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Move client to right directory
        run: |
          mkdir -p ./clients/python
          mv python-client/* ./clients/python/
          rm -rf python-client

      - name: Set short sha
        id: sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Commit generated files
        run: |
          git add clients/python/
          git commit -m "Update DJ Python client"
          git checkout -b ci-pr/python-client-${{ steps.sha.outputs.short_sha }}
          git push --set-upstream origin ci-pr/python-client-${{ steps.sha.outputs.short_sha }}

      - name: Open a PR
        run: gh pr create -B main -H ci-pr/python-client-${{ steps.sha.outputs.short_sha }} --title 'Update Python Client - ${{ steps.sha.outputs.short_sha }}' --body '(This PR was generated by a GitHub action)'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
