name: Release
on:
  push:
    branches: [ main ]
    paths:
      - 'dj/__about__.py'
      - 'client/python/datajunction/__about__.py'

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: |
          python -m pip install --upgrade pip
          pip install hatch

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - uses: dorny/paths-filter@v2
        id: changes
        with:
           filters: |
              server:
                - 'dj/__about__.py'
              client:
                - 'client/python/datajunction/__about__.py'
              djrs:
                - 'djrs/djrs/__about__.py'
              djqs:
                - 'djqs/djqs/__about__.py'

      - name: Tag release
        working-directory: ${{ steps.changes.outputs.server == 'true' && '.' || steps.changes.outputs.client == 'true' && './client/python' || steps.changes.outputs.djrs == 'true' && './djrs' || steps.changes.outputs.djqs == 'true' && './djqs' }}
        run: |
          export NEW_VERSION=v$(hatch version)
          export LIBRARY=${{ steps.changes.outputs.server == 'true' && 'server' || steps.changes.outputs.client == 'true' && 'client' || steps.changes.outputs.djrs == 'true' && 'djrs' || steps.changes.outputs.djqs == 'true' && 'djqs' }}
          git tag -a $NEW_VERSION-$LIBRARY -m $NEW_VERSION-$LIBRARY
          git push origin $NEW_VERSION-$LIBRARY
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}

      - name: Publish to pypi
        working-directory: ${{ steps.changes.outputs.server == 'true' && '.' || steps.changes.outputs.client == 'true' && './client/python' || steps.changes.outputs.djrs == 'true' && './djrs' || steps.changes.outputs.djqs == 'true' && './djqs' }}
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
        run: |
          hatch build
          hatch publish

      - name: Create Github release
        working-directory: ${{ steps.changes.outputs.server == 'true' && '.' || steps.changes.outputs.client == 'true' && './client/python' || steps.changes.outputs.djrs == 'true' && './djrs' || steps.changes.outputs.djqs == 'true' && './djqs' }}
        run: |
          export LIBRARY=${{ steps.changes.outputs.server == 'true' && 'server' || steps.changes.outputs.client == 'true' && 'client' || steps.changes.outputs.djrs == 'true' && 'djrs' || steps.changes.outputs.djqs == 'true' && 'djqs' }}
          gh release create $(hatch version)-$LIBRARY
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
